language: java

sudo: false
addons:
  apt:
    packages:
    - ant
    - ant-optional
    - junit4
    - libhamcrest-java

cache:
  apt: true
  directories:
  - fred/
  - fred/lib/

before_install:
  - mkdir -p fred/lib/freenet/
  - if [ ! -e fred/lib/bcprov-jdk15on-154.jar ]; then cd fred/lib ; wget -c --no-check-certificate https://bouncycastle.org/download/bcprov-jdk15on-154.jar; cd ../.. ; fi
  - if [ ! -e fred/src ]; then git clone https://github.com/freenet/fred.git --branch next --single-branch fred ; fi
  - cd fred ; git pull ; cd ..
  - if [ ! -e fred/dist/freenet.jar ]; then cd fred ; ant -Dlib.contrib.get=true -Dtest.skip=true ; cd .. ; fi

script: ant

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
